packages:
  - apps/*
  - libs/*
  - packages/*

catalog:
  '@commitlint/types': ^20.4.0
  '@mjwheatley/nx-vitest-config': 0.4.1
  '@nx/vite': 22.5.1
  '@vitest/coverage-v8': ^4.0.18
  commitlint: ^20.4.2
  vitest: ^4.0.18
  vitest-sonar-reporter: ^3.0.0
  zod: ^4.3.6

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  micromatch@<4.0.8: '>=4.0.8'
  minimatch@<10.2.1: '>=10.2.1'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tmp@<=0.2.3: '>=0.2.4'
